# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

distro_apt:
  Debian:
    components:
      - main
      - contrib
    mirror: http://deb.debian.org/debian
    security: http://security.debian.org/debian-security
    aws_mirror: http://cdn-aws.deb.debian.org/debian
    aws_security: http://cdn-aws.deb.debian.org/debian-security
  Ubuntu:
    components:
      - main
      - universe
    mirror: http://archive.ubuntu.com/ubuntu
    security: http://security.ubuntu.com/ubuntu
    aws_mirror: http://cdn-aws.archive.ubuntu.com/ubuntu
    aws_security: http://cdn-aws.archive.ubuntu.com/ubuntu-security
