# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: CC-BY-SA-3.0

# baseurl is the location of the generated site from the browser's
# perspective (e.g., http://doc.arvados.org or
# file:///tmp/arvados/doc/.site). To make docs show up inside
# workbench, use /doc here and add a symlink at
# apps/workbench/public/doc pointing to ../../../doc/.site
# You can also set these on the command line:
# $ rake generate baseurl=/example arvados_api_host=example.com

baseurl:
current_version:
all_versions:
arvados_api_host: localhost
arvados_cluster_uuid: local
arvados_workbench_host: http://localhost

exclude: ["Rakefile", "tmp", "vendor"]

navbar:
  userguide:
    - Welcome:
      - user/index.html.textile.liquid
      - user/getting_started/community.html.textile.liquid
    - Walkthough:
      - user/tutorials/wgs-tutorial.html.textile.liquid
    - Using Workbench:
      - user/getting_started/workbench.html.textile.liquid
      - user/tutorials/tutorial-workflow-workbench.html.textile.liquid
      - user/topics/workbench-migration.html.textile.liquid
    - Working at the Command Line:
      - user/getting_started/setup-cli.html.textile.liquid
      - user/reference/api-tokens.html.textile.liquid
      - user/getting_started/check-environment.html.textile.liquid
    - Access an Arvados virtual machine:
      - user/getting_started/vm-login-with-webshell.html.textile.liquid
      - user/getting_started/ssh-access-unix.html.textile.liquid
      - user/getting_started/ssh-access-windows.html.textile.liquid
    - Working with data sets:
      - user/tutorials/tutorial-keep.html.textile.liquid
      - user/tutorials/tutorial-keep-get.html.textile.liquid
      - user/tutorials/tutorial-keep-mount-gnu-linux.html.textile.liquid
      - user/tutorials/tutorial-keep-mount-os-x.html.textile.liquid
      - user/tutorials/tutorial-keep-mount-windows.html.textile.liquid
      - user/tutorials/tutorial-keep-collection-lifecycle.html.textile.liquid
      - user/topics/arv-copy.html.textile.liquid
      - user/topics/collection-versioning.html.textile.liquid
      - user/topics/storage-classes.html.textile.liquid
    - Data Analysis with Workflows:
      - user/cwl/arvados-vscode-training.html.md.liquid
      - user/cwl/rnaseq-cwl-training.html.textile.liquid
      - user/cwl/cwl-runner.html.textile.liquid
      - user/cwl/cwl-run-options.html.textile.liquid
      - user/tutorials/writing-cwl-workflow.html.textile.liquid
      - user/topics/arv-docker.html.textile.liquid
      - user/cwl/cwl-style.html.textile.liquid
      - user/cwl/cwl-extensions.html.textile.liquid
      - user/cwl/federated-workflows.html.textile.liquid
      - user/cwl/cwl-versions.html.textile.liquid
      - user/cwl/crunchstat-summary.html.textile.liquid
      - user/cwl/costanalyzer.html.textile.liquid
      - user/debugging/container-shell-access.html.textile.liquid
    - Working with git repositories:
      - user/tutorials/add-new-repository.html.textile.liquid
      - user/tutorials/git-arvados-guide.html.textile.liquid
    - Reference:
      - user/topics/link-accounts.html.textile.liquid
      - user/reference/cookbook.html.textile.liquid
    - Arvados License:
      - user/copying/copying.html.textile.liquid
      - user/copying/agpl-3.0.html
      - user/copying/LICENSE-2.0.html
      - user/copying/by-sa-3.0.html
  sdk:
    - Overview:
      - sdk/index.html.textile.liquid
    - Python:
      - sdk/python/sdk-python.html.textile.liquid
      - sdk/python/example.html.textile.liquid
      - sdk/python/python.html.textile.liquid
      - sdk/python/arvados-fuse.html.textile.liquid
      - sdk/python/arvados-cwl-runner.html.textile.liquid
      - sdk/python/cookbook.html.textile.liquid
      - sdk/python/events.html.textile.liquid
    - CLI:
      - sdk/cli/install.html.textile.liquid
      - sdk/cli/index.html.textile.liquid
      - sdk/cli/reference.html.textile.liquid
      - sdk/cli/subcommands.html.textile.liquid
      - sdk/cli/project-management.html.textile.liquid
    - Go:
      - sdk/go/index.html.textile.liquid
      - sdk/go/example.html.textile.liquid
    - R:
      - sdk/R/index.html.md
      - sdk/R/arvados/index.html.textile.liquid
    - Ruby:
      - sdk/ruby/index.html.textile.liquid
      - sdk/ruby/example.html.textile.liquid
    - Java v2:
      - sdk/java-v2/index.html.textile.liquid
      - sdk/java-v2/example.html.textile.liquid
      - sdk/java-v2/javadoc.html.textile.liquid
    - Perl:
      - sdk/perl/index.html.textile.liquid
      - sdk/perl/example.html.textile.liquid
  api:
    - Concepts:
      - api/index.html.textile.liquid
      - api/tokens.html.textile.liquid
      - api/requests.html.textile.liquid
      - api/methods.html.textile.liquid
      - api/resources.html.textile.liquid
    - Permission and authentication:
      - api/methods/api_client_authorizations.html.textile.liquid
      - api/methods/api_clients.html.textile.liquid
      - api/methods/authorized_keys.html.textile.liquid
      - api/methods/groups.html.textile.liquid
      - api/methods/users.html.textile.liquid
      - api/methods/user_agreements.html.textile.liquid
    - System resources:
      - api/methods/keep_services.html.textile.liquid
      - api/methods/links.html.textile.liquid
      - api/methods/logs.html.textile.liquid
      - api/methods/nodes.html.textile.liquid
      - api/methods/virtual_machines.html.textile.liquid
      - api/methods/keep_disks.html.textile.liquid
    - Data management:
      - api/keep-webdav.html.textile.liquid
      - api/keep-s3.html.textile.liquid
      - api/keep-web-urls.html.textile.liquid
      - api/projects.html.textile.liquid
      - api/methods/collections.html.textile.liquid
      - api/methods/repositories.html.textile.liquid
    - Container engine:
      - api/methods/container_requests.html.textile.liquid
      - api/methods/containers.html.textile.liquid
      - api/methods/workflows.html.textile.liquid
    - Management (admin/system):
      - api/dispatch.html.textile.liquid
    - Jobs engine (legacy):
      - api/crunch-scripts.html.textile.liquid
      - api/methods/jobs.html.textile.liquid
      - api/methods/job_tasks.html.textile.liquid
      - api/methods/pipeline_instances.html.textile.liquid
      - api/methods/pipeline_templates.html.textile.liquid
    - Metadata for bioinformatics (deprecated):
      - api/methods/humans.html.textile.liquid
      - api/methods/specimens.html.textile.liquid
      - api/methods/traits.html.textile.liquid
  architecture:
    - Topics:
      - architecture/index.html.textile.liquid
    - Storage in Keep:
      - architecture/storage.html.textile.liquid
      - architecture/keep-components-overview.html.textile.liquid
      - architecture/keep-clients.html.textile.liquid
      - architecture/keep-data-lifecycle.html.textile.liquid
      - architecture/manifest-format.html.textile.liquid
    - Computation with Crunch:
      - api/execution.html.textile.liquid
      - architecture/dispatchcloud.html.textile.liquid
      - architecture/hpc.html.textile.liquid
      - architecture/singularity.html.textile.liquid
    - Other:
      - api/permission-model.html.textile.liquid
      - architecture/federation.html.textile.liquid
  admin:
    - Topics:
      - admin/index.html.textile.liquid
    - Users and Groups:
      - admin/user-management.html.textile.liquid
      - admin/user-management-cli.html.textile.liquid
      - admin/group-management.html.textile.liquid
      - admin/reassign-ownership.html.textile.liquid
      - admin/link-accounts.html.textile.liquid
      - admin/federation.html.textile.liquid
      - admin/merge-remote-account.html.textile.liquid
      - admin/migrating-providers.html.textile.liquid
      - user/topics/arvados-sync-external-sources.html.textile.liquid
      - admin/scoped-tokens.html.textile.liquid
      - admin/token-expiration-policy.html.textile.liquid
    - Monitoring:
      - admin/logging.html.textile.liquid
      - admin/metrics.html.textile.liquid
      - admin/health-checks.html.textile.liquid
      - admin/management-token.html.textile.liquid
      - admin/user-activity.html.textile.liquid
    - Data Management:
      - admin/collection-versioning.html.textile.liquid
      - admin/collection-managed-properties.html.textile.liquid
      - admin/restricting-upload-download.html.textile.liquid
      - admin/keep-balance.html.textile.liquid
      - admin/controlling-container-reuse.html.textile.liquid
      - admin/logs-table-management.html.textile.liquid
      - admin/metadata-vocabulary.html.textile.liquid
      - admin/storage-classes.html.textile.liquid
      - admin/keep-recovering-data.html.textile.liquid
      - admin/keep-measuring-deduplication.html.textile.liquid
    - Cloud:
      - admin/spot-instances.html.textile.liquid
      - admin/cloudtest.html.textile.liquid
    - Other:
      - install/migrate-docker19.html.textile.liquid
      - admin/upgrade-crunch2.html.textile.liquid
  installguide:
    - Overview:
      - install/index.html.textile.liquid
    - Docker quick start:
      - install/arvbox.html.textile.liquid
    - Installation with Salt:
      - install/salt-single-host.html.textile.liquid
      - install/salt-multi-host.html.textile.liquid
    - Arvados on Kubernetes:
      - install/arvados-on-kubernetes.html.textile.liquid
      - install/arvados-on-kubernetes-minikube.html.textile.liquid
      - install/arvados-on-kubernetes-GKE.html.textile.liquid
    - Manual installation:
      - install/install-manual-prerequisites.html.textile.liquid
      - install/packages.html.textile.liquid
    - Configuration:
      - install/config.html.textile.liquid
      - admin/config-urls.html.textile.liquid
      - admin/config.html.textile.liquid
    - Maintenance and upgrading:
      - admin/upgrading.html.textile.liquid
      - admin/maintenance-and-upgrading.html.textile.liquid
    - Core:
      - install/install-api-server.html.textile.liquid
    - Keep:
      - install/install-keepstore.html.textile.liquid
      - install/configure-fs-storage.html.textile.liquid
      - install/configure-s3-object-storage.html.textile.liquid
      - install/configure-azure-blob-storage.html.textile.liquid
      - install/install-keepproxy.html.textile.liquid
      - install/install-keep-web.html.textile.liquid
      - install/install-keep-balance.html.textile.liquid
    - User interface:
      - install/setup-login.html.textile.liquid
      - install/install-ws.html.textile.liquid
      - install/install-workbench-app.html.textile.liquid
      - install/install-workbench2-app.html.textile.liquid
      - install/install-composer.html.textile.liquid
    - Additional services:
      - install/install-shell-server.html.textile.liquid
      - install/install-webshell.html.textile.liquid
      - install/install-arv-git-httpd.html.textile.liquid
    - Containers API (all):
      - install/install-jobs-image.html.textile.liquid
    - Containers API (cloud):
      - install/crunch2-cloud/install-compute-node.html.textile.liquid
      - install/crunch2-cloud/install-dispatch-cloud.html.textile.liquid
    - Compute nodes (Slurm or LSF):
      - install/crunch2/install-compute-node-docker.html.textile.liquid
      - install/crunch2/install-compute-node-singularity.html.textile.liquid
    - Containers API (Slurm):
      - install/crunch2-slurm/install-dispatch.html.textile.liquid
      - install/crunch2-slurm/configure-slurm.html.textile.liquid
      - install/crunch2-slurm/install-test.html.textile.liquid
    - Containers API (LSF):
      - install/crunch2-lsf/install-dispatch.html.textile.liquid
    - Additional configuration:
      - install/container-shell-access.html.textile.liquid
    - External dependencies:
      - install/install-postgresql.html.textile.liquid
      - install/ruby.html.textile.liquid
      - install/nginx.html.textile.liquid
      - install/install-docker.html.textile.liquid
