# Do not use this file for site configuration. Create application.yml
# instead (see application.yml.example).

development:
  cache_classes: false
  eager_load: true
  consider_all_requests_local: true
  action_controller.perform_caching: false
  action_mailer.raise_delivery_errors: false
  active_support.deprecation: :log
  action_dispatch.best_standards_support: :builtin
  assets.debug: true
  profiling_enabled: true
  site_name: Arvados Workbench (dev)
  local_modified: <%= '-modified' if `git status -s` %>

production:
  force_ssl: true
  cache_classes: true
  eager_load: true
  consider_all_requests_local: false
  action_controller.perform_caching: true
  serve_static_assets: false
  assets.compile: false
  assets.digest: true
  i18n.fallbacks: true
  active_support.deprecation: :notify
  profiling_enabled: false

  arvados_insecure_https: false

  data_import_dir: /data/arvados-workbench-upload/data
  data_export_dir: /data/arvados-workbench-download/data

  site_name: Arvados Workbench

test:
  cache_classes: true
  eager_load: false
  serve_static_assets: true
  static_cache_control: public, max-age=3600
  consider_all_requests_local: true
  action_controller.perform_caching: false
  action_dispatch.show_exceptions: false
  action_controller.allow_forgery_protection: false
  action_mailer.delivery_method: :test
  active_support.deprecation: :stderr
  profiling_enabled: false
  secret_token: <%= rand(2**256).to_s(36) %>
  secret_key_base: <%= rand(2**256).to_s(36) %>

  # When you run the Workbench's integration tests, it starts the API
  # server as a dependency.  These settings should match the API
  # server's Rails defaults.  If you adjust those, change these
  # settings in application.yml to match.
  arvados_login_base: https://localhost:3001/login
  arvados_v1_base: https://localhost:3001/arvados/v1
  arvados_insecure_https: true

  site_name: Workbench:test

  # Enable user profile with one required field
  user_profile_form_fields:
    - key: organization
      type: text
      form_field_title: Institution
      form_field_description: Your organization
      required: true
    - key: role
      type: select
      form_field_title: Your role
      form_field_description: Choose the category that best describes your role in your organization.
      options:
        - Bio-informatician
        - Computational biologist
        - Biologist or geneticist
        - Software developer
        - IT
        - Other

common:
  assets.js_compressor: false
  assets.css_compressor: false
  data_import_dir: /tmp/arvados-workbench-upload
  data_export_dir: /tmp/arvados-workbench-download
  arvados_login_base: https://arvados.local/login
  arvados_v1_base: https://arvados.local/arvados/v1
  arvados_insecure_https: true
  activation_contact_link: mailto:info@arvados.org
  arvados_docsite: http://doc.arvados.org
  arvados_theme: default
  show_user_agreement_inline: false
  secret_token: ~
  secret_key_base: false
  default_openid_prefix: https://www.google.com/accounts/o8/id
  send_user_setup_notification_email: true

  # Set user_profile_form_fields to enable and configure the user profile page.
  # Default is set to false. A commented setting with full description is provided below.
  user_profile_form_fields: false

  # Below is a sample setting of user_profile_form_fields config parameter.
  # This configuration parameter should be set to either false (to disable) or
  # to an array as shown below. 
  # Configure the list of input fields to be displayed in the profile page
  # using the attribute "key" for each of the input fields.
  # This sample shows configuration with one required and one optional form fields.
  # For each of these input fields:
  #   You can specify "type" as "text" or "select".
  #   List the "options" to be displayed for each of the "select" menu.
  #   Set "required" as "true" for any of these fields to make them required.
  # If any of the required fields are missing in the user's profile, the user will be
  # redirected to the profile page before they can access any Workbench features.
  #user_profile_form_fields:
  #  - key: organization
  #    type: text
  #    form_field_title: Institution/Company
  #    form_field_description: Your organization
  #    required: true
  #  - key: role
  #    type: select
  #    form_field_title: Your role
  #    form_field_description: Choose the category that best describes your role in your organization.
  #    options:
  #      - Bio-informatician
  #      - Computational biologist
  #      - Biologist or geneticist
  #      - Software developer
  #      - IT
  #      - Other

  # Use "user_profile_form_message" to configure the message you want to display on
  # the profile page.
  user_profile_form_message: Welcome to Arvados. All <span style="color:red">required fields</span> must be completed before you can proceed.

  # source_version
  source_version: "<%= `git log -n 1 --format=%h` %>"
  local_modified: false

  # report notification to and from addresses
  issue_reporter_email_from: arvados@example.com
  issue_reporter_email_to: arvados@example.com
  support_email_address: arvados@example.com

  # Configuration for diagnostics testing. Use this to enable diagnostics testing for an env.
  diagnostics_testing_user_tokens: false
  diagnostics_testing_pipeline_fields: false

  # Below is a sample setting for diagnostics testing.
  # Configure test user tokens as "diagnostics_testing_user_tokens".
  #   At this time the tests need an "active" user token.
  # Also, configure the pipelines to be executed as "diagnostics_testing_pipeline_fields".
  # For each of the pipeline fields:
  #   You 
  #diagnostics_testing_user_tokens:
  #  active: eu33jurqntstmwo05h1jr3eblmi961e802703y6657s8zb14r
  #  admin: eu33jurqntstmwo05h1jr3eblmi961e802703y6657s8zb14r
  #diagnostics_testing_pipeline_fields:
  #  tutorial pipeline:
  #    template_uuid: zzzzz-p5p6p-rxj8d71854j9idn
  #    input_names: ['Diagnostic testing - Tutorial pipeline input']
  #  tutorial pipeline 2:
  #    template_uuid: zzzzz-p5p6p-kfwus81of6y3ezs
  #    input_names: ['Diagnostic testing - Tutorial pipeline input']
